<div class="tyc">
<h3>T&eacute;rminos y condiciones de uso del Sitio</h3>
<p>Este contrato describe los t&eacute;rminos y condiciones generales (los "<strong>T&eacute;rminos y Condiciones Generales</strong>") aplicables al uso de los servicios ofrecidos por <strong>SoloChanguitas SRL</strong>, CUIT 23-32952457-4. Cualquier persona (en adelante "Usuario" o en plural "Usuarios") que desee acceder y/o usar el sitio o los Servicios podr&aacute; hacerlo sujet&aacute;ndose a los T&eacute;rminos y Condiciones Generales respectivos, junto con todas las dem&aacute;s pol&iacute;ticas y principios que rigen <strong>SoloChanguitas.com</strong> y que son incorporados al presente.</p>
<p class="tyc-lead">CUALQUIER PERSONA QUE NO ACEPTE ESTOS T&Eacute;RMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CAR&Aacute;CTER OBLIGATORIO Y VINCULANTE, DEBER&Aacute; ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</p>
<p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los T&eacute;rminos y Condiciones Generales y en las Pol&iacute;ticas de Privacidad as&iacute; como en los dem&aacute;s documentos incorporados a los mismos por referencia, previo a su registraci&oacute;n como Usuario de <strong>SoloChanguitas.com</strong></p>
<h4>01 - Capacidad</h4>
<p>Los Servicios s&oacute;lo est&aacute;n disponibles para personas que tengan capacidad legal para contratar. No podr&aacute;n utilizar los servicios las personas que no tengan esa capacidad, los menores de edad o Usuarios de <strong>SoloChanguitas</strong> que hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si est&aacute;s registrando un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los t&eacute;rminos de este Acuerdo.</p>
<h4>02 - Registraci&oacute;n</h4>
<p>Es obligatorio completar el formulario de registraci&oacute;n en todos sus campos con datos v&aacute;lidos para poder utilizar los servicios que brinda <strong>SoloChanguitas</strong>. El futuro Usuario deber&aacute; completarlo con su informaci&oacute;n personal de manera exacta, precisa y verdadera ("Mi perfil") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. <strong>SoloChanguitas</strong> podr&aacute; utilizar diversos medios para identificar a sus Usuarios, pero <strong>SoloChanguitas</strong> NO se responsabiliza por la certeza de los Datos Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.</p>
<p>A su exclusiva discreci&oacute;n, <strong>SoloChanguitas</strong> podr&aacute; requerir una registraci&oacute;n adicional a los Usuarios que operen como empresas y necesiten contratar m&aacute;s de 100 personas mensualmente, como requisito para que dichos Usuarios accedan a paquetes especiales de publicaciones. En estos casos, una vez efectuada la registraci&oacute;n adicional, las ofertas de trabajo s&oacute;lo se publicar&aacute;n en <strong>SoloChanguitas</strong> a trav&eacute;s de alguno de dichos paquetes o bajo las modalidades que <strong>SoloChanguitas</strong> habilite para este tipo de Usuarios.</p>
<p><strong>SoloChanguitas</strong> se reserva el derecho de solicitar alg&uacute;n comprobante y/o dato adicional a efectos de corroborar los Datos Personales, as&iacute; como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitaci&oacute;n, se dar&aacute; de baja todos los art&iacute;culos publicados, as&iacute; como las ofertas realizadas, sin que ello genere alg&uacute;n derecho a resarcimiento.</p>
<p>El Usuario acceder&aacute; a su cuenta personal ("Cuenta") mediante el ingreso de su Apodo/ Mail y clave de seguridad personal elegida ("Clave de Seguridad"). El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad.</p>
<p>La Cuenta es personal, &uacute;nica e intransferible, y est&aacute; prohibido que un mismo Usuario registre o posea m&aacute;s de una Cuenta. En caso que <strong>SoloChanguitas</strong> detecte distintas Cuentas que contengan datos coincidentes o relacionados, podr&aacute; cancelar, suspender o inhabilitarlas. El Usuario ser&aacute; responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma est&aacute; restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a <strong>SoloChanguitas</strong> en forma inmediata y por medio id&oacute;neo y fehaciente, cualquier uso no autorizado de su Cuenta, as&iacute; como el ingreso por terceros no autorizados a la misma. Se aclara que est&aacute; prohibida la venta, cesi&oacute;n o transferencia de la Cuenta (incluyendo la reputaci&oacute;n y calificaciones) bajo ning&uacute;n t&iacute;tulo. <strong>SoloChanguitas</strong> se reserva el derecho de rechazar cualquier solicitud de registraci&oacute;n o de cancelar una registraci&oacute;n previamente aceptada, sin que est&eacute; obligado a comunicar o exponer las razones de su decisi&oacute;n y sin que ello genere alg&uacute;n derecho a indemnizaci&oacute;n o resarcimiento.</p>
<h4>03 - Modificaciones del Acuerdo</h4>
<p><strong>SoloChanguitas</strong> podr&aacute; modificar los T&eacute;rminos y Condiciones Generales en cualquier momento haciendo p&uacute;blicos en el Sitio los t&eacute;rminos modificados. Todos los t&eacute;rminos modificados entrar&aacute;n en vigor a los 10 (diez) d&iacute;as de su publicaci&oacute;n. Dentro de los 5 (cinco) d&iacute;as siguientes a la publicaci&oacute;n de las modificaciones introducidas, el Usuario deber&aacute; comunicar v&iacute;a e-mail si no acepta las mismas; en ese caso quedar&aacute; disuelto el v&iacute;nculo contractual y ser&aacute; inhabilitado como Usuario siempre que no tenga deudas pendientes. Vencido este plazo, se considerar&aacute; que el Usuario acepta los nuevos t&eacute;rminos y el contrato continuar&aacute; vinculando a ambas partes.</p>
<h4>04 - Listado de Bienes</h4>
<h5>Utilizaci&oacute;n de MercadoPago</h5>
<p>Al publicar un anuncio en el Sitio, el usuario vendedor consiente expresamente la utilizaci&oacute;n de MercadoPago como una de las formas disponibles para el pago del bien o servicio ofrecido y se obliga a no modificar en nada el precio de venta del bien o servicio si el trabajador decidiera utilizar MercadoPago. Asimismo, el usuario declara que ha le&iacute;do, comprendido y aceptado los T&eacute;rminos y Condiciones de utilizaci&oacute;n de dicho servicio.</p>
<h5>Publicaci&oacute;n de bienes y/o servicios</h5>
<p>El Usuario deber&aacute; ofrecer a la venta los bienes y promover los servicios en las categor&iacute;as y subcategor&iacute;as apropiadas. Las publicaciones podr&aacute;n incluir textos descriptivos, gr&aacute;ficos, fotograf&iacute;as y otros contenidos y condiciones pertinentes para la venta del bien o la promoci&oacute;n del servicio, siempre que no violen ninguna disposici&oacute;n de este acuerdo o dem&aacute;s pol&iacute;ticas de <strong>SoloChanguitas</strong>. El producto ofrecido por el Usuario Vendedor debe ser exactamente descrito en cuanto a sus condiciones y caracter&iacute;sticas relevantes. Se entiende y presume que mediante la inclusi&oacute;n del bien o servicio en <strong>SoloChanguitas</strong>, el Usuario acepta que tiene la intenci&oacute;n y el derecho de concretar la compra/venta del bien o servicio por &eacute;l ofrecido, o est&aacute; facultado para ello por su titular y posee el bien disponible para su entrega inmediata. Se establece que los precios de los productos y servicios publicados deber&aacute;n ser expresados con IVA incluido cuando corresponda la aplicaci&oacute;n del mismo, y en moneda de curso legal. <strong>SoloChanguitas</strong> podr&aacute; remover cualquier publicaci&oacute;n cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final por la realizaci&oacute;n del servicio o compra/ venta del producto. Se deja expresamente establecido que ninguna descripci&oacute;n podr&aacute; contener datos personales o de contacto, tales como, y sin limitarse a, n&uacute;meros telef&oacute;nicos, direcci&oacute;n de e-mail, direcci&oacute;n postal, direcciones de p&aacute;ginas de Internet que contengan datos como los mencionados anteriormente. No podr&aacute; publicitarse otros medios de pagos, distintos de los enunciados por <strong>SoloChanguitas</strong> en la p&aacute;gina de publicaci&oacute;n de art&iacute;culos. En caso que se infrinja cualquiera de las disposiciones establecidas en esta cl&aacute;usula, <strong>SoloChanguitas</strong> podr&aacute; editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicaci&oacute;n donde se encuentre la infracci&oacute;n y en ning&uacute;n caso se devolver&aacute;n o bonificar&aacute;n los cargos de publicaci&oacute;n.</p>
<h5>Inclusi&oacute;n de im&aacute;genes y fotograf&iacute;as</h5>
<p>El usuario puede incluir im&aacute;genes y fotograf&iacute;as del producto ofrecido siempre que las mismas se correspondan con el art&iacute;culo, salvo que se trate de bienes o productos o de servicios que por su naturaleza no lo permiten.</p>
<p><strong>SoloChanguitas</strong> podr&aacute; impedir la publicaci&oacute;n de la fotograf&iacute;a, e incluso del producto, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes T&eacute;rminos y Condiciones.</p>
<h5>Art&iacute;culos Prohibidos</h5>
<p>S&oacute;lo podr&aacute;n ser ingresados en las listas de bienes ofrecidos y/o servicios publicados, aquellos cuya venta no se encuentre t&aacute;cita o expresamente prohibida en los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>SoloChanguitas</strong> o por la ley vigente.</p>
<h5>Protecci&oacute;n de Propiedad Intelectual</h5>
<p>Los bienes y servicios publicados no deben infringir los derechos de propiedad intelectual e industrial y cualesquiera otros de terceros. Quienes sean titulares de derechos podr&aacute;n identificar y solicitar la remoci&oacute;n de aquellos art&iacute;culos que a su criterio infrinjan o violen sus derechos. En caso que <strong>SoloChanguitas</strong> sospeche que se est&aacute; cometiendo o se ha cometido una actividad il&iacute;cita o infractora de derechos de propiedad intelectual o industrial, <strong>SoloChanguitas</strong> se reserva el derecho de adoptar todas las medidas que entienda adecuadas incluyendo la .suspensi&oacute;n del servicio.</p>
<h4>05 - Privacidad de la Informaci&oacute;n</h4>
<p>Para utilizar los Servicios ofrecidos por <strong>SoloChanguitas</strong>, los Usuarios deber&aacute;n facilitar determinados datos de car&aacute;cter personal. Su informaci&oacute;n personal se procesa y almacena en servidores o medios magn&eacute;ticos que mantienen altos est&aacute;ndares de seguridad y protecci&oacute;n tanto f&iacute;sica como tecnol&oacute;gica.</p>
<h4>06 - Obligaciones de los Usuarios</h4>
<h5>Obligaciones del Comprador</h5>
<p>Durante el plazo fijado por el Usuario oferente del bien o servicio, los Usuarios interesados realizar&aacute;n ofertas de compra para los bienes y podr&aacute;n realizar preguntas a los oferentes de los servicios. La oferta de venta se cierra una vez que vence el plazo o se acaban las cantidades estipuladas por el Vendedor y la promoci&oacute;n del servicio culmina con el vencimiento del plazo de la publicaci&oacute;n.</p>
<p>El Usuario seleccionado por el Usuario oferente del bien o servicio est&aacute; obligado a intentar comunicarse con el Usuario oferente del buen o servicio y completar la operaci&oacute;n, salvo que la operaci&oacute;n est&eacute; prohibida por la ley o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>SoloChanguitas</strong>, en cuyo caso no estar&aacute; obligado a concretar la operaci&oacute;n.</p>
<p>Al seleccionar un Usuario para la compra de un bien o realizaci&oacute;n de un servicio, acepta quedar obligado por las condiciones de venta incluidas en la descripci&oacute;n del art&iacute;culo en la medida en que las mismas no infrinjan las leyes o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>SoloChanguitas</strong>. La oferta de compra o contrataci&oacute;n del servicio es irrevocable salvo en circunstancias excepcionales, tales como que el vendedor cambie sustancialmente la descripci&oacute;n del bien o servicio despu&eacute;s de realizada alguna oferta, que exista un claro error tipogr&aacute;fico, o que no pueda verificar la identidad del oferente.</p>
<p>Las selecciones de los Usuarios que comprar&aacute;n los bienes o realizar&aacute;n los servicios s&oacute;lo ser&aacute;n consideradas v&aacute;lidas una vez que hayan sido procesadas por el sistema inform&aacute;tico de <strong>SoloChanguitas</strong>.</p>
<h5>Impuestos</h5>
<p>Tal como lo establece la normativa fiscal vigente, el comprador o personal de servicios debe exigir factura o ticket al vendedor o empleador como comprobante de la operaci&oacute;n. El vendedor o empleador no estar&aacute; obligado a emitir factura o ticket, s&oacute;lo en el caso de tratarse de una persona f&iacute;sica que efect&uacute;a ventas o brinda servicios ocasionalmente, o de acuerdo a la legislaci&oacute;n que rija la operaci&oacute;n.</p>
<h5>Obligaciones del Vendedor o Empleador</h5>
<p>El Usuario Vendedor o Empleador debe tener capacidad legal para vender el bien objeto de su oferta o contratar personal.</p>
<p>Si el Usuario Vendedor o Empleador ha recibido al menos una oferta sobre el precio m&iacute;nimo que estableci&oacute;, queda obligado a intentar comunicarse con el Comprador o Personal de Servicios y completar la operaci&oacute;n. Solamente en casos excepcionales el Vendedor o Empleador podr&aacute; retractarse de la venta u oferta de trabajo, tales como cuando no haya podido acordar con el Usuario Comprador o Personal de Servicios sobre la forma de pago, de entrega o no sea posible verificar la verdadera identidad o dem&aacute;s informaci&oacute;n del Comprador o Personal de Servicios.</p>
<p><strong>SoloChanguitas</strong> tendr&aacute; el derecho de requerir, conforme los criterios que considere pertinentes, que ciertos Usuarios Vendedores o Empleadores solamente anuncien sus bienes o servicios en el Sitio Web mediante la utilizaci&oacute;n de los Servicios de Gesti&oacute;n de Pagos online de MercadoPago y/o otras herramientas ofrecidas por <strong>SoloChanguitas</strong> para el cobro del bien vendido y de las tarifas por la utilizaci&oacute;n de los servicios, importando eventualmente en el pago de tarifas aplicables por la utilizaci&oacute;n de los mismos.</p>
<p>Dado que <strong>SoloChanguitas</strong> es un punto de encuentro entre Comprador/ Personal de Servicios y Vendedor/ Empleador y no participa de las operaciones que se realizan entre ellos, el Vendedor o Empleador ser&aacute; responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus art&iacute;culos o realizaci&oacute;n de los servicios publicados, sin que pudiera imput&aacute;rsele a <strong>SoloChanguitas</strong> alg&uacute;n tipo de responsabilidad por incumplimientos en tal sentido.</p>
<p>Cuando el Vendedor o Empleador haya recibido una oferta en un art&iacute;culo por &eacute;l publicado, deber&aacute; calificar a la contraparte de acuerdo a lo establecido en los T&eacute;rminos y Condiciones Generales.</p>
<h5>Impuestos</h5>
<p>Como se menciona anteriormente, <strong>SoloChanguitas</strong> s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite comunicarse mediante Internet para encontrar una forma de vender o comprar art&iacute;culos y/o servicios. <strong>SoloChanguitas</strong> no tiene participaci&oacute;n alguna en el proceso de negociaci&oacute;n y perfeccionamiento del contrato definitivo entre las partes. Por eso, <strong>SoloChanguitas</strong> no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.</p>
<h4>07 - Prohibiciones</h4>
<p>Los Usuarios no podr&aacute;n: (a) manipular los precios de los art&iacute;culos; (b) mantener ning&uacute;n tipo de comunicaci&oacute;n por e-mail, o por cualquier otro medio (incluyendo las redes sociales) durante la oferta del bien o servicio con ninguno de los Usuarios que participan en la misma, salvo en la secci&oacute;n de Preguntas y Respuestas; (c) dar a conocer sus datos personales o de otros usuarios a trav&eacute;s de la secci&oacute;n de Preguntas y Respuestas y/o por alg&uacute;n otro medio (incluyendo pero sin limitar Twitter, Facebook y/ o cualquier otra red social); (e) aceptar datos personales proporcionados por otros usuarios a trav&eacute;s de la secci&oacute;n de Preguntas y Respuestas y/o alg&uacute;n otro medio (incluyendo pero sin limitar Twitter, Facebook y/o cualquier otra red social); (e) publicar o vender art&iacute;culos prohibidos por los T&eacute;rminos y Condiciones Generales, dem&aacute;s pol&iacute;ticas de <strong>SoloChanguitas</strong> o leyes vigentes; (f) insultar o agredir a otros Usuarios; (g) utilizar su reputaci&oacute;n, calificaciones, comentarios o r&eacute;plicas recibidas en el sitio de <strong>SoloChanguitas</strong> en cualquier &aacute;mbito fuera de <strong>SoloChanguitas</strong>.</p>
<p>Este tipo de actividades ser&aacute; investigado por <strong>SoloChanguitas</strong> y el infractor podr&aacute; ser sancionado con la suspensi&oacute;n o cancelaci&oacute;n de la oferta e incluso de su inscripci&oacute;n como Usuario de <strong>SoloChanguitas</strong> y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuraci&oacute;n de delitos o contravenciones o los perjuicios civiles que pueda causar a los Usuarios oferentes.</p>
<h4>08 - Violaciones del Sistema o Bases de Datos</h4>
<p>No est&aacute; permitida ninguna acci&oacute;n o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de <strong>SoloChanguitas</strong> como en las ofertas, descripciones, cuentas o bases de datos de <strong>SoloChanguitas</strong>. Cualquier intromisi&oacute;n, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato har&aacute;n pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, as&iacute; como lo har&aacute; responsable de indemnizar los da&ntilde;os ocasionados.</p>
<h4>09 - Sanciones. Suspensi&oacute;n de operaciones</h4>
<p>Sin perjuicio de otras medidas, <strong>SoloChanguitas</strong> podr&aacute; advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o una publicaci&oacute;n, aplicar una sanci&oacute;n que impacte negativamente en la reputaci&oacute;n de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestaci&oacute;n de sus Servicios si (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>SoloChanguitas</strong>; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de <strong>SoloChanguitas</strong> en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier informaci&oacute;n proporcionada por el mismo fuere err&oacute;nea; (e) <strong>SoloChanguitas</strong> entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las public&oacute;, para <strong>SoloChanguitas</strong> o para los Usuarios. En el caso de la suspensi&oacute;n o inhabilitaci&oacute;n de un Usuario, todos los art&iacute;culos que tuviera publicados ser&aacute;n removidos del sistema y en ning&uacute;n caso se devolver&aacute;n o bonificar&aacute;n los cargos de publicaci&oacute;n involucrados. Tambi&eacute;n se remover&aacute;n del sistema las ofertas de compra de bienes ofrecidos en subasta.</p>
<h4>10 - Responsabilidad</h4>
<p><strong>SoloChanguitas</strong> s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite ponerse en comunicaci&oacute;n mediante Internet para encontrar una forma de vender o comprar servicios o bienes. <strong>SoloChanguitas</strong> no es el propietario de los art&iacute;culos ofrecidos, ni empleador de las ofertas de trabajo publicadas, ni responde por los t&eacute;rminos empleados que puedan surgir del intercambio; no tiene posesi&oacute;n de los biens ni los ofrece en venta. <strong>SoloChanguitas</strong> no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no ser&aacute; responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes o servicios ofrecidos, adquiridos o enajenados por los Usuarios, as&iacute; como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los art&iacute;culos que publica para venta o servicio y por las ofertas y/o compras que realiza.</p>
<p>Debido a que <strong>SoloChanguitas</strong> no tiene ninguna participaci&oacute;n durante todo el tiempo en que el art&iacute;culo se publica para la venta, ni en la posterior negociaci&oacute;n y perfeccionamiento del contrato definitivo entre las partes, no ser&aacute; responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operaci&oacute;n. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ning&uacute;n caso <strong>SoloChanguitas</strong> ser&aacute; responsable por lucro cesante, o por cualquier otro da&ntilde;o y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por art&iacute;culos publicados a trav&eacute;s de <strong>SoloChanguitas</strong>.</p>
<p><strong>SoloChanguitas</strong> recomienda actuar con prudencia y sentido com&uacute;n al momento de realizar operaciones con otros Usuarios. El Usuario debe tener presentes, adem&aacute;s, los riesgos de contratar menores o personas que se valgan de una identidad falsa. <strong>SoloChanguitas</strong> NO ser&aacute; responsable por la realizaci&oacute;n de ofertas y/o operaciones con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por <strong>SoloChanguitas</strong>.</p>
<p>En caso que uno o m&aacute;s Usuarios o alg&uacute;n tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a <strong>SoloChanguitas</strong> y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados.</p>
<p>En virtud que el usuario Vendedor o Empleador tiene la facultad para eliminar preguntas o impedir a un usuario hacer preguntas u ofertas en sus publicaciones, se deja aclarado que en ese caso, el usuario ser&aacute; el exclusivo responsable por esa decisi&oacute;n y las consecuencias que pudieran acarrear.</p>
<h4>11 - Alcance de los servicios de SoloChanguitas</h4>
<p>Este acuerdo no crea ning&uacute;n contrato de sociedad, de mandato, de franquicia, o relaci&oacute;n laboral entre <strong>SoloChanguitas</strong> y el Usuario. El Usuario reconoce y acepta que <strong>SoloChanguitas</strong> no es parte en ninguna operaci&oacute;n, ni tiene control alguno sobre la calidad, seguridad o legalidad de los art&iacute;culos anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar, emplear o ser empleados. <strong>SoloChanguitas</strong> no puede asegurar que un Usuario completar&aacute; una operaci&oacute;n o trabajo ni podr&aacute; verificar la identidad o Datos Personales ingresados por los Usuarios. <strong>SoloChanguitas</strong> no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no ser&aacute; responsable por la correspondencia o acuerdos que el Usuario celebre con dichos terceros o con otros Usuarios.</p>
<h4>12 - Fallas en el sistema</h4>
<p><strong>SoloChanguitas</strong> no se responsabiliza por cualquier da&ntilde;o, perjuicio o p&eacute;rdida al Usuario causados por fallas en el sistema, en el servidor o en Internet. <strong>SoloChanguitas</strong> tampoco ser&aacute; responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a ra&iacute;z de cualquier transferencia de datos, archivos, im&aacute;genes, textos, o audio contenidos en el mismo. Los Usuarios NO podr&aacute;n imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades t&eacute;cnicas o fallas en los sistemas o en Internet. <strong>SoloChanguitas</strong> no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades t&eacute;cnicas o fallas de Internet, o por cualquier otra circunstancia ajena a <strong>SoloChanguitas</strong>; en tales casos se procurar&aacute; restablecerlo con la mayor celeridad posible sin que por ello pueda imput&aacute;rsele alg&uacute;n tipo de responsabilidad.</p>
<h4>13 - Tarifas. Facturaci&oacute;n</h4>
<p>La registraci&oacute;n en <strong>SoloChanguitas</strong> es gratuita. El Usuario se obliga a abonar a <strong>SoloChanguitas</strong> la Tarifa, los cargos por publicaci&oacute;n o por cualquier otro servicio prestado por <strong>SoloChanguitas</strong> por el cual haya establecida una tarifa vigente. <strong>SoloChanguitas</strong> se reserva el derecho de modificar, cambiar, agregar, o eliminar las tarifas vigentes, en cualquier momento, lo cual ser&aacute; notificado a los Usuarios. Sin embargo, <strong>SoloChanguitas</strong> podr&aacute; modificar temporalmente la Pol&iacute;tica de Tarifas y las tarifas por sus servicios por raz&oacute;n de promociones, siendo efectivas estas modificaciones cuando se haga p&uacute;blica la promoci&oacute;n o se realice el anuncio. <strong>SoloChanguitas</strong> se reserva el derecho de tomar las medidas judiciales y extrajudiciales que estime pertinentes para obtener el pago del monto debido. En caso de haberse facturado cargos que no hubiesen correspondido, el Usuario deber&aacute; comunicarse con nuestro equipo de Atenci&oacute;n al Cliente para resolver dicha cuesti&oacute;n. </p>
<h4>14 - Sistema de reputaci&oacute;n</h4>
<p>Debido a que la verificaci&oacute;n de la identidad de los Usuarios en Internet es dif&iacute;cil, <strong>SoloChanguitas</strong> no puede confirmar ni confirma la identidad pretendida de cada Usuario. Por ello el Usuario cuenta con un sistema de reputaci&oacute;n de Usuarios que es actualizado peri&oacute;dicamente en base a datos vinculados con su actividad en el sitio y a los comentarios ingresados por los Usuarios seg&uacute;n las operaciones que hayan realizado. Tanto aquellos Usuarios que hayan resultado ganadores de una oferta o contratados, como el Vendedor o Empleador, deber&aacute;n ingresar una calificaci&oacute;n informando acerca de la concreci&oacute;n o no de la operaci&oacute;n; tambi&eacute;n podr&aacute;n ingresar un comentario si as&iacute; lo desean. Este sistema de reputaci&oacute;n, adem&aacute;s constar&aacute; de un espacio donde los Usuarios podr&aacute;n hacer comentarios y r&eacute;plicas a las calificaciones recibidas y acceder a los mismos. Dichos comentarios ser&aacute;n incluidos bajo exclusiva responsabilidad de los Usuarios que los emitan. En virtud que las calificaciones, comentarios y r&eacute;plicas son realizados por los Usuarios, &eacute;stos ser&aacute;n incluidos bajo exclusiva responsabilidad de los Usuarios que los emitan. <strong>SoloChanguitas</strong> no tiene obligaci&oacute;n de verificar la veracidad o exactitud de los mismos y NO se responsabiliza por los dichos all&iacute; vertidos por cualquier Usuario, por las ofertas de compras o ventas que los Usuarios realicen teni&eacute;ndolos en cuenta o por la confianza depositada en las calificaciones de la contraparte o por cualquier otro comentario expresado dentro del sitio o a trav&eacute;s de cualquier otro medio incluido el correo electr&oacute;nico. <strong>SoloChanguitas</strong> se reserva el derecho de eliminar aquellos comentarios que sean considerados inadecuados u ofensivos. <strong>SoloChanguitas</strong> mantiene el derecho de suspender preventivamente o excluir a aquellos Usuarios que sean objeto de comentarios negativos provenientes de fuentes distintas.</p>
<h4>15 - Propiedad intelectual. Enlaces</h4>
<p>Los contenidos de las pantallas relativas a los servicios de <strong>SoloChanguitas</strong> como as&iacute; tambi&eacute;n los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de <strong>SoloChanguitas</strong> y est&aacute;n protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y dise&ntilde;os industriales. El uso indebido y la reproducci&oacute;n total o parcial de dichos contenidos quedan prohibidos, salvo autorizaci&oacute;n expresa y por escrito de <strong>SoloChanguitas</strong>.</p>
<p>El Sitio puede contener enlaces a otros sitios web lo cual no indica que sean propiedad u operados por <strong>SoloChanguitas</strong>. En virtud que <strong>SoloChanguitas</strong> no tiene control sobre tales sitios, NO ser&aacute; responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por da&ntilde;os o p&eacute;rdidas ocasionadas por la utilizaci&oacute;n de los mismos, sean causadas directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relaci&oacute;n, aprobaci&oacute;n, respaldo de <strong>SoloChanguitas</strong> a dichos sitios y sus contenidos.</p>
<h4>16 - Indemnizaci&oacute;n</h4>
<p>El Usuario indemnizar&aacute; y mantendr&aacute; indemne a <strong>SoloChanguitas</strong>, sus filiales, empresas controladas y/o controlantes, directivos, administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o terceros por sus actividades en el Sitio o por su incumplimiento los T&eacute;rminos y Condiciones Generales y dem&aacute;s Pol&iacute;ticas que se entienden incorporadas al presente o por la violaci&oacute;n de cualesquiera leyes o derechos de terceros, incluyendo los honorarios de abogados.</p>
<h4>17 - Anexos</h4>
<p>Forman parte integral e inseparable de los T&eacute;rminos y Condiciones Generales, los siguientes documentos y/o secciones de <strong>SoloChanguitas</strong> incorporados por referencia, donde se detallan pol&iacute;ticas y/o T&eacute;rminos y Condiciones de diferentes servicios ofrecidos en el sitio. </p>
<h4>18 - Jurisdicci&oacute;n y Ley Aplicable</h4>
<p>Este acuerdo estar&aacute; regido en todos sus puntos por las leyes vigentes en la Rep&uacute;blica Argentina. Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretaci&oacute;n, alcance o cumplimiento, ser&aacute; sometida al arbitraje del Centro Empresarial de Mediaci&oacute;n y Arbitraje, de acuerdo con la reglamentaci&oacute;n vigente de dicho tribunal. La sede de dicho arbitraje ser&aacute; la Ciudad de Buenos Aires y los procedimientos se llevar&aacute;n a cabo en idioma castellano.</p>
<h4>19 - Domicilio</h4>
<p>Se fija como domicilio de <strong>SoloChanguitas SRL</strong> la calle Gallo 1683 5to J, Capital Federal, c&oacute;digo postal 1425, Rep&uacute;blica Argentina. Si tienes alguna duda sobre los T&eacute;rminos y Condiciones Generales o dem&aacute;s pol&iacute;ticas y principios que rigen <strong>SoloChanguitas</strong> consulta nuestra p&aacute;gina de <a href="#/faq">Preguntas frecuentes</a> o env&iacute;a un formulario de <a href="#/contacto">Contacto</a>.</p>
</div>