<h3>Pol&iacute;ticas de privacidad y confidencialidad de la informaci&oacute;n</h3>
<p>Estas "Pol&iacute;ticas de Privacidad" entrar&aacute;n en vigor desde su aceptaci&oacute;n para los nuevos usuarios y est&aacute;n vigentes desde el 21 de Septiembre de 2013.</p>
<p>Como parte normal de nuestra actividad recogemos y, en algunos casos, revelamos informaci&oacute;n sobre nuestros usuarios y visitantes de nuestro sitio Web. Estas Pol&iacute;ticas de Privacidad describen la informaci&oacute;n que SoloChanguitas recoge sobre sus usuarios y visitantes y lo que puede hacerse con dicha informaci&oacute;n. Esta pol&iacute;tica es muy detallada porque es importante que todos los usuarios y visitantes de nuestro sitio Web conozcan las pr&aacute;cticas de SoloChanguitas de la forma m&aacute;s precisa posible. Al registrarse y/o navegar el sitio Web de SoloChanguitas, el usuario y/o el visitante presta su consentimiento para que se utilice su informaci&oacute;n personal de acuerdo a las pol&iacute;ticas que se describen a continuaci&oacute;n.</p>
<p>La privacidad de la informaci&oacute;n de los usuarios es muy importante para SoloChanguitas. Es por esa raz&oacute;n que se toman las precauciones y recaudos para resguardar su informaci&oacute;n, utilizando los mecanismos de seguridad inform&aacute;tica de protecci&oacute;n de la informaci&oacute;n m&aacute;s completos y eficaces.</p>
<p>Este documento es parte integrante de los <a href="#/condiciones">T&eacute;rminos y Condiciones Generales de SoloChanguitas</a>. Mediante la aceptaci&oacute;n de los T&eacute;rminos y Condiciones Generales en el momento de la registraci&oacute;n el usuario acepta las pol&iacute;ticas aqu&iacute; contenidas.</p>
<h4>Derechos de acceso, cancelaci&oacute;n y rectificaci&oacute;n de la informaci&oacute;n personal</h4>
<p>Los usuarios tienen reconocidos y podr&aacute;n ejercitar los derechos de acceder, cancelar y actualizar su Informaci&oacute;n Personal, incluyendo su direcci&oacute;n de e-mail, as&iacute; como a oponerse al tratamiento de la misma y a ser informado de las cesiones llevadas a cabo, todo ello de conformidad a lo dispuesto en la normativa aplicable. Conforme se establece en el art&iacute;culo 14, inciso 3 de la Ley N&deg; 25.326, el titular de los datos personales, previa acreditaci&oacute;n de su identidad, tiene la facultad de ejercer el derecho de acceso a los mismos, dentro de los 10 (diez) d&iacute;as corridos desde la acreditaci&oacute;n de su identidad, en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un inter&eacute;s leg&iacute;timo al efecto. Para la rectificaci&oacute;n y supresi&oacute;n de los datos personales, el titular de los mismo podr&aacute; ejercer tales derechos dentro de los 5 (cinco) d&iacute;as h&aacute;biles de acreditada su identidad.</p>
<p>Los usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de la Informaci&oacute;n Personal facilitada, y se comprometen a mantenerla debidamente actualizada.</p>
<p>Una vez registrado en SoloChanguitas, el usuario podr&aacute; revisar y cambiar la informaci&oacute;n que nos ha enviado durante el proceso de registraci&oacute;n incluyendo:</p>
<ul>
    <li>El Apodo y direcci&oacute;n de correo electr&oacute;nico. Sin perjuicio de los cambios que realice, SoloChanguitas conservar&aacute; la Informaci&oacute;n Personal anterior por motivos de seguridad y control del fraude.</li>
<li>La informaci&oacute;n de la registraci&oacute;n como: compa&ntilde;&iacute;a, domicilio, ciudad, regi&oacute;n, c&oacute;digo postal, n&uacute;mero principal de tel&eacute;fono, n&uacute;mero secundario de tel&eacute;fono, n&uacute;mero de fax, correo electr&oacute;nico, etc.</li>
<li>Clave.</li>
</ul>
<p>En determinados casos, mantendremos en nuestros archivos Informaci&oacute;n Personal que nos hayas pedido que retiremos, y ello con la finalidad de resolver disputas o reclamaciones, detectar problemas o incidencias y solucionarlos, y dar cumplimiento a lo dispuesto en los T&eacute;rminos y Condiciones Generales por un per&iacute;odo de tiempo determinado por la ley. En cualquier caso, la Informaci&oacute;n Personal de un usuario no ser&aacute; inmediatamente retirada de nuestros archivos por motivos legales y t&eacute;cnicos, incluyendo sistemas de soportes de seguridad. Por tanto, no se debe esperar que toda la Informaci&oacute;n Personal sea definitivamente borrada de nuestras bases de datos.</p>
<p>Los usuarios deben actualizar su Informaci&oacute;n Personal peri&oacute;dicamente conforme vaya cambiando para que los otros usuarios puedan ubicarlos cuando realicen una operaci&oacute;n. Para hacer cualquier modificaci&oacute;n en la informaci&oacute;n que suministrada en el momento de la Registraci&oacute;n, se debe ingresar en la secci&oacute;n Mi Perfil.</p>
<p>SoloChanguitas podr&aacute; modificar en cualquier momento los t&eacute;rminos y condiciones de estas Pol&iacute;ticas de Privacidad y confidencialidad y/o las pr&aacute;cticas de env&iacute;o de e-mails. Si decidimos introducir alg&uacute;n cambio material a nuestras Pol&iacute;ticas de Privacidad, te notificaremos publicando una versi&oacute;n actualizada de las Pol&iacute;ticas en esta secci&oacute;n o mediante el env&iacute;o de un e-mail o inform&aacute;ndolo en la p&aacute;gina principal u otras secciones del sitio para mantenerte actualizado de los cambios realizados.</p>
<p>Si hacemos cambios materiales en la forma que tu Informaci&oacute;n Personal es administrada te notificaremos por e-mail para que puedas tomar una decisi&oacute;n informada respecto si aceptas o no que tu Informaci&oacute;n Personal sea utilizada de esa forma. Si no aceptas esos t&eacute;rminos, en ese caso quedar&aacute; disuelto el v&iacute;nculo contractual y tu Informaci&oacute;n Personal no ser&aacute; usada de otra forma que la que fue informada al momento de recabarse.</p>
<p>Para mayor informaci&oacute;n sobre la confidencialidad de tu Informaci&oacute;n Personal, cont&aacute;ctanos por correo electr&oacute;nico o postal. </p>
<p>Se informa que la Direcci&oacute;n Nacional de Protecci&oacute;n de Datos Personales, &Oacute;rgano de Control de la Ley N&deg; 25.326, tiene la atribuci&oacute;n de atender las denuncias y reclamos que se interpongan con relaci&oacute;n al incumplimiento de las normas sobre protecci&oacute;n de datos personales.</p>
<p>Por correo ordinario a: Arias 3751, piso 7, Capital Federal, c&oacute;digo postal C1430CRF, Rep&uacute;blica Argentina.</p>
<p>Por favor cont&aacute;ctate con nosotros.</p>
<h4>La informaci&oacute;n que recabamos</h4>
<p>Lo primero que se debe hacer para disfrutar de los servicios de SoloChanguitas es registrarse, suministrando ciertos datos personales ("Informaci&oacute;n Personal") completos y exactos. Podremos solicitar, recabar y almacenar la siguiente Informaci&oacute;n Personal: apodo o seud&oacute;nimo para operar en el sitio de SoloChanguitas, nombre, n&uacute;mero de documento o identificaci&oacute;n v&aacute;lida, informaci&oacute;n f&iacute;sica de contacto (como n&uacute;mero de tel&eacute;fono domicilio, direcci&oacute;n de e-mail, etc.). SoloChanguitas podr&aacute; confirmar los datos personales suministrados acudiendo a entidades p&uacute;blicas, compa&ntilde;&iacute;as especializadas o centrales de riesgo, para lo cual nos autorizas expresamente. La informaci&oacute;n que SoloChanguitas obtenga de estas entidades ser&aacute; tratada en forma confidencial.</p>
<p>El Usuario que se registre en SoloChanguitas a trav&eacute;s de su cuenta personal en una red social ("Cuenta Personal"), o de cualquier modo acceda a SoloChanguitas a trav&eacute;s de su Cuenta Personal, consiente expresamente que SoloChanguitas:</p>
<ul>
    <li>Tenga acceso, en cualquier momento, a la totalidad de la informaci&oacute;n contenida en su Cuenta Personal, incluyendo en particular, pero sin limitaci&oacute;n, a su Informaci&oacute;n Personal, informaci&oacute;n sobre sus intereses, gustos, contactos y cualquier otro contenido alojado en su Cuenta Personal;</li>
<li>Incluya en dicha cuenta, mensajes, fotograf&iacute;as, videos y cualquier otro tipo de contenido; y</li>
<li>Env&iacute;e al correo electr&oacute;nico del Usuario vinculado a la Cuenta Personal, informaci&oacute;n o mensajes con la finalidad descripta en la secci&oacute;n "Uso que hacemos de la Informaci&oacute;n" abajo.</li>
</ul>
<p>SoloChanguitas recoge y almacena autom&aacute;ticamente cierta informaci&oacute;n sobre la actividad de los usuarios y visitantes dentro de su sitio web. Tal informaci&oacute;n puede incluir la URL de la que provienen (est&eacute;n o no en nuestro sitio web), a qu&eacute; URL acceden seguidamente (est&eacute;n o no en nuestro sitio web), qu&eacute; navegador est&aacute;n usando, y sus direcciones IP. Tambi&eacute;n las p&aacute;ginas visitadas, las b&uacute;squedas realizadas, las publicaciones, compras o ventas, calificaciones y r&eacute;plicas ingresadas, mensajes en los foros, entre otra informaci&oacute;n podr&aacute; ser almacenada y retenida.</p>
<p>Si los usuarios nos env&iacute;an correspondencia sean correos electr&oacute;nicos o cartas, o si otros usuarios o terceros nos env&iacute;an correspondencia sobre las actividades o sobre los mensajes de otros usuarios en nuestro sitio, podemos recoger y almacenar tal Informaci&oacute;n Personal, incluyendo direcciones de e-mail.</p>
<h4>Uso que hacemos de la informaci&oacute;n</h4>
<p>Para suministrar un excelente servicio y para que los usuarios puedan realizar operaciones en forma &aacute;gil y segura, SoloChanguitas requiere cierta informaci&oacute;n de car&aacute;cter personal, incluyendo direcci&oacute;n de e-mail. La recolecci&oacute;n de informaci&oacute;n nos permite ofrecer a los usuarios servicios y funcionalidades que se adecuen mejor a sus necesidades y personalizar nuestros servicios para hacer que sus experiencias con SoloChanguitas sean lo m&aacute;s c&oacute;modas posible. La Informaci&oacute;n Personal que recabamos tiene las siguientes finalidades:</p>
<ul>
    <li>Ayudar al Comprador/ Contratado y Vendedor o Empleador a entrar en contacto directo en la oportunidad que corresponda seg&uacute;n la modalidad de la compra. En este caso, SoloChanguitas suministrar&aacute; a los interesados sus datos personales (nombre, tel&eacute;fonos, localidad y correo electr&oacute;nico), a trav&eacute;s de correo electr&oacute;nico o a trav&eacute;s del sitio. La informaci&oacute;n as&iacute; conocida por el comprador o el vendedor, s&oacute;lo podr&aacute; ser utilizada a efectos de concluir la operaci&oacute;n originada en SoloChanguitas y no deber&aacute; ser empleada por ninguno de ellos con fines publicitarios o promocionales u otras actividades no relacionadas con SoloChanguitas, salvo la expresa autorizaci&oacute;n del usuario.</li>
<li>Desarrollar estudios internos sobre los intereses, comportamientos y demograf&iacute;a de los usuarios para comprender mejor sus necesidades e intereses y ofrecer mejores servicios o proveerles informaci&oacute;n relacionada.</li>
<li>Mejorar nuestras iniciativas comerciales y promocionales y analizar las p&aacute;ginas visitadas las b&uacute;squedas realizadas por los usuarios, para mejorar nuestra oferta de contenidos y art&iacute;culos, personalizar dichos contenidos, su presentaci&oacute;n y servicios.</li>
<li>Enviar informaci&oacute;n o mensajes por e-mail sobre nuevos servicios, mostrar publicidad o promociones, banners, de inter&eacute;s para nuestros usuarios, noticias sobre SoloChanguitas, adem&aacute;s de la informaci&oacute;n expresamente autorizada en la secci&oacute;n de preferencias. Si el usuario lo prefiere, puede solicitar que lo excluyan de las listas para el env&iacute;o de informaci&oacute;n promocional o publicitaria. Por favor aprende a hacerlo la secci&oacute;n "Cambio de preferencias de e-mail" abajo.</li>
<li>Enviar informaci&oacute;n o avisos por mensajes cortos de texto (SMS) al tel&eacute;fono celular suministrado por el usuario a SoloChanguitas. Los mensajes cortos de texto podr&aacute;n contener (sin limitarse a) informaci&oacute;n sobre los servicios de SoloChanguitas, que podr&aacute; incluir claves personales para el uso de dichos servicios y recordatorios de vencimientos de pagos y otras obligaciones adquiridas por el uso de tales servicios.</li>
<li>Los ganadores de las Promociones y/o concursos realizados por SoloChanguitas autorizan expresamente a difundir sus nombres, datos personales e im&aacute;genes y los de sus familias, por los medios y en las formas que consideren convenientes, con fines publicitarios y/o promocionales, sin derecho a compensaci&oacute;n alguna.</li>
<li>Compartir la informaci&oacute;n Personal (incluyendo direcci&oacute;n de e-mail) con los proveedores de servicios o las empresas de "outsourcing" que contribuyan a mejorar o facilitar las operaciones a trav&eacute;s de SoloChanguitas, como (sin limitarse a) servicios de transporte, medios de pago, seguros o intermediarios en la gesti&oacute;n de pagos, call centers o programas de fidelidad, entre otros. SoloChanguitas velar&aacute; porque se cumplan ciertos est&aacute;ndares, mediante la firma de acuerdos o convenios cuyo objeto sea la privacidad de los datos personales de nuestros usuarios. En algunos casos, estos proveedores de servicios ser&aacute;n quienes recojan informaci&oacute;n directamente del usuario (por ejemplo si les solicitamos que realicen encuestas o estudios). En tales casos, podr&aacute; recibir una notificaci&oacute;n acerca de la participaci&oacute;n de un proveedor de servicios en tales actividades, y quedar&aacute; a discreci&oacute;n del usuario toda la informaci&oacute;n que quiera brindarle y los usos adicionales que los proveedores decidan hacer. En caso de que facilites, por propia iniciativa informaci&oacute;n adicional a dichos prestadores de servicios directamente, tales Prestadores usar&aacute;n esta informaci&oacute;n conforme a sus propias pol&iacute;ticas de privacidad. SoloChanguitas no se hace responsable por el uso indebido de la Informaci&oacute;n Personal del usuario que hagan compa&ntilde;&iacute;as o sitios de Internet que act&uacute;en por cuenta propia.</li>
<li>Si decidimos revelar o compartir Informaci&oacute;n Persona con terceros que no son proveedores de servicios o empresas afiliadas o relacionadas con SoloChanguitas, requeriremos tu consentimiento.</li>
<h4>Confidencialidad de la informaci&oacute;n</h4>
<p>Una vez registrado en su sitio Web, SoloChanguitas no vender&aacute;, alquilar&aacute; o compartir&aacute; la Informaci&oacute;n Personal excepto en las formas establecidas en estas pol&iacute;ticas. Sin perjuicio de ello, el usuario consiente en forma expresa que SoloChanguitas transfiera total o parcialmente la Informaci&oacute;n Personal a cualquiera de las sociedades controladas, controlantes y/o vinculadas con SoloChanguitas, a cualquier t&iacute;tulo y en el momento, forma y condiciones que estime pertinentes. Haremos todo lo que est&eacute; a nuestro alcance para proteger la privacidad de la informaci&oacute;n. Puede suceder que en virtud de &oacute;rdenes judiciales, o de regulaciones legales, nos veamos compelidos a revelar informaci&oacute;n a las autoridades o terceras partes bajo ciertas circunstancias, o bien en casos que terceras partes puedan interceptar o acceder a cierta informaci&oacute;n o transmisiones de datos en cuyo caso SoloChanguitas no responder&aacute; por la informaci&oacute;n que sea revelada.</p>
<h4>Apodo</h4>
<p>Para interactuar dentro del sitio, los usuarios deben utilizar un apodo que los identificar&aacute;. Los usuarios no tendr&aacute;n acceso a la informaci&oacute;n personal de los otros usuarios, salvo en el caso de los ofertantes de una Subasta Exclusiva y cuando hayan realizado con ellos alguna operaci&oacute;n a trav&eacute;s de nuestra plataforma, luego de la cual ambas partes recibir&aacute;n la informaci&oacute;n de la otra.</p>
<h4>Clave Personal</h4>
<p>Para acceder a los servicios reservados &uacute;nicamente para los usuarios debidamente registrados los usuarios dispondr&aacute;n de una clave personal. Con ella podr&aacute;n comprar, vender, ofertar, calificar, entre otras actividades. Esta clave deben mantenerla bajo absoluta confidencialidad y, en ning&uacute;n caso, deber&aacute;n revelarla o compartirla con otras personas.</p>
<p>El usuario ser&aacute; responsable de todos los actos que tengan lugar mediante el uso de su Apodo y Clave, lo que incluye hacerse cargo del pago de las tarifas que eventualmente se devenguen o por los perjuicios que puedan sufrir otros usuarios por tal motivo. Si por cualquier raz&oacute;n un usuario creyera que alguien puede conocer su clave, deber&aacute; modificarla ingresando desde el men&uacute; de navegaci&oacute;n en Mi perfil.</p>
<h4>Menores de Edad</h4>
<p>Nuestros servicios s&oacute;lo est&aacute;n disponibles para aquellas personas que tengan capacidad legal para contratar. Por lo tanto, aquellos que no cumplan con esta condici&oacute;n deber&aacute;n abstenerse de suministrar informaci&oacute;n personal para ser incluida en nuestras bases de datos. Sin embargo, pueden hacerlo a trav&eacute;s de los padres o tutores.</p>
<h4>El uso de la informaci&oacute;n por otros Usuarios</h4>
<p>Para facilitar la interacci&oacute;n entre todos los miembros de la comunidad de SoloChanguitas, nuestro servicio permite un acceso limitado a ciertos datos de contacto del resto de usuarios, tales como Nombre de usuario, Tel&eacute;fonos, Ciudad y direcci&oacute;n de correo electr&oacute;nico.</p>
<p>Los usuarios s&oacute;lo podr&aacute;n utilizar la Informaci&oacute;n Personal de otros usuarios obtenida en el sitio para: (a) comunicaciones relacionadas con SoloChanguitas que no constituyan comunicaciones comerciales no solicitadas, (b) utilizar servicios ofrecidos en SoloChanguitas (por ejemplo: dep&oacute;sito, seguros, env&iacute;o o transporte y reclamaciones sobre fraude), y (c) cualquier otra finalidad a la que el usuario correspondiente consienta expresamente una vez le hayan sido comunicadas previamente la informaci&oacute;n legalmente requerida.</p>
<p>Bajo ninguna circunstancia, se debe comunicar Informaci&oacute;n Personal o direcci&oacute;n de correo electr&oacute;nico de otro usuario a ning&uacute;n tercero sin nuestro consentimiento y el del usuario afectado. No se debe agregar a la agenda de direcciones de correo electr&oacute;nico (f&iacute;sica o electr&oacute;nica) los datos de ning&uacute;n usuario de SoloChanguitas, ni siquiera los datos de quienes hayan adquirido alg&uacute;n art&iacute;culo ofrecido en SoloChanguitas, sin que medie el consentimiento expreso de tal usuario.</p>
<h4>Cookies</h4>
<p>El usuario y el visitante del sitio Web de SoloChanguitas conoce y acepta que SoloChanguitas podr&aacute; utilizar un sistema de seguimiento mediante la utilizaci&oacute;n de cookies (las "Cookies"). Las Cookies son peque&ntilde;os archivos que se instalan en el disco r&iacute;gido, con una duraci&oacute;n limitada en el tiempo que ayudan a personalizar los servicios. Tambi&eacute;n ofrecemos ciertas funcionalidades que s&oacute;lo est&aacute;n disponibles mediante el empleo de Cookies. Las Cookies se utilizan con el fin de conocer los intereses, el comportamiento y la demograf&iacute;a de quienes visitan o son usuarios de nuestro Sitio Web y de esa forma, comprender mejor sus necesidades e intereses y darles un mejor servicio o proveerle informaci&oacute;n relacionada. Tambi&eacute;n usaremos la informaci&oacute;n obtenida por intermedio de las Cookies para analizar las p&aacute;ginas navegadas por el visitante o usuario, las b&uacute;squedas realizadas, mejorar nuestras iniciativas comerciales y promocionales, mostrar publicidad o promociones, banners de inter&eacute;s, noticias sobre SoloChanguitas, perfeccionar nuestra oferta de contenidos y art&iacute;culos, personalizar dichos contenidos, presentaci&oacute;n y servicios; tambi&eacute;n podremos utilizar Cookies para promover y hacer cumplir las reglas y seguridad del sitio. SoloChanguitas podr&aacute; agregar Cookies en los e-mails que env&iacute;e para medir la efectividad de las promociones.</p>
<p>Utilizamos adicionalmente las Cookies para que el usuario no tenga que introducir su clave tan frecuentemente durante una sesi&oacute;n de navegaci&oacute;n, tambi&eacute;n para contabilizar y corroborar las registraciones, la actividad del usuario y otros conceptos o acuerdos comerciales, siempre teniendo como objetivo de la instalaci&oacute;n de las Cookies, el beneficio del usuario que la recibe, y no ser&aacute; usado con otros fines ajenos a SoloChanguitas. Se establece que la instalaci&oacute;n, permanencia y existencia de las Cookies en el computador del usuario depende de su exclusiva voluntad y puede ser eliminada de su computador cuando el usuario as&iacute; lo desee. Para saber como quitar las Cookies del sistema es necesario revisar la secci&oacute;n Ayuda (Help) del navegador.   Adicionalmente, se pueden encontrar Cookies u otros sistemas similares instalados por terceros en ciertas p&aacute;ginas de nuestro sitio Web. Por ejemplo, al navegar por una p&aacute;gina creada por un usuario, puede que exista una Cookie emplazada en tal p&aacute;gina.</p>
<p>Se aclara expresamente que estas pol&iacute;ticas cubre la utilizaci&oacute;n de Cookies por este sitio y no la utilizaci&oacute;n de Cookies por parte de anunciantes. Nosotros no controlamos el uso de Cookies por terceros.</p>
<h4>Web Beacons</h4>
<p>Un Web beacon es una imagen electr&oacute;nica, tambi&eacute;n llamada single-pixel (1 x 1) o pixel transparente, que es colocada en c&oacute;digo de una p&aacute;gina Web. Un Web beacon tiene finalidades similares a las Cookies. Adicionalmente un Web beacon es utilizado para medir patrones de tr&aacute;fico de los usuarios de una p&aacute;gina a otra con el objeto de maximizar como fluye el tr&aacute;fico a trav&eacute;s de la Web. El usuario y el visitante del sitio Web de SoloChanguitas conoce y acepta que SoloChanguitas podr&aacute; utilizar un sistema de seguimiento mediante la utilizaci&oacute;n de Web beacons.</p>
<h4>Env&iacute;ale esta oferta de trabajo a un amigo</h4>
<p>Si eliges usar el servicio "Env&iacute;a esta oferta de trabajo a un amigo", SoloChanguitas podr&aacute; requerir el nombre y correo electr&oacute;nico de la persona a quien se le remita. A trav&eacute;s de esta funcionalidad, SoloChanguitas enviar&aacute; un e-mail autom&aacute;tico invit&aacute;ndolo a visitar cierto producto en el sitio Web. SoloChanguitas utilizar&aacute; el correo electr&oacute;nico de la persona a quien se le remita s&oacute;lo para enviarle esta comunicaci&oacute;n y posterior seguimiento, sin embargo dicha informaci&oacute;n no ser&aacute; almacenada.</p>
<p>De acuerdo a su Pol&iacute;tica de Privacidad, SoloChanguitas toma los recaudos necesarios para evitar el env&iacute;o no solicitado de e-mails. Adem&aacute;s SoloChanguitas y sus usuarios no aceptan el "spamming" o env&iacute;o no solicitado de correos electr&oacute;nicos. Por ello se establece que est&aacute; absolutamente prohibida la utilizaci&oacute;n del servicio Env&iacute;ale este art&iacute;culo a un amigo con fines de spam, o env&iacute;o indiscriminado de mensajes de cualquier naturaleza por correo electr&oacute;nico, con cualquier finalidad que esto se realice. Por favor, no les env&iacute;es este tipo de mensajes a quienes as&iacute; te lo soliciten.</p>
<p>SoloChanguitas podr&aacute; suspender o inhabilitar definitivamente a aquellos usuarios que utilicen este servicio con los fines de promocionar sus art&iacute;culos a la venta o cualquier otro fin distinto al previsto por este servicio y que sean denunciados por aquellas personas que reciben tales mensajes.</p>
<p>Cualquier persona que no desee recibir estas comunicaciones por e-mail, deber&aacute; requerirlo.</p>
    SoloChanguitas no se hace responsable del uso que el vendedor, el comprador, cualquier usuario u otra persona pudieran hacer de la informaci&oacute;n publicada.</p>
    <h4>Orden de autoridades competentes - Requerimientos Legales</h4>
<p>SoloChanguitas coopera con las autoridades competentes y con otros terceros para garantizar el cumplimiento de las leyes, por ejemplo en materia de protecci&oacute;n de derechos de propiedad industrial e intelectual, prevenci&oacute;n del fraude y otras materias.</p>
<p>SoloChanguitas podr&aacute; revelar la Informaci&oacute;n Personal de sus usuarios bajo requerimiento de la autoridades judiciales o gubernamentales competentes para efectos de investigaciones conducidas por ellas, aunque no exista una orden ni una citaci&oacute;n ejecutiva o judicial, o por ejemplo (y sin limitaci&oacute;n a este supuesto) cuando se trate de investigaciones de car&aacute;cter penal o de fraude o las relacionadas con pirater&iacute;a inform&aacute;tica o la violaci&oacute;n de derechos de autor. En tales situaciones, SoloChanguitas colaborar&aacute; con las autoridades competentes con el fin de salvaguardar la integridad y la seguridad de la Comunidad y la de sus usuarios.</p>
<p>SoloChanguitas puede (y los usuarios lo autorizan expresamente) comunicar cualquier Informaci&oacute;n Personal sobre sus usuarios con la finalidad de cumplir la normativa aplicable y cooperar con las autoridades competentes en la medida en que discrecionalmente lo entendamos necesario y adecuado en relaci&oacute;n con cualquier investigaci&oacute;n de un il&iacute;cito o un fraude, infracci&oacute;n de derechos de propiedad industrial o intelectual, u otra actividad que sea ilegal o que pueda exponer a SoloChanguitas o a sus usuarios a cualquier responsabilidad legal. Adem&aacute;s, podemos (y los usuarios lo autorizan expresamente) comunicar su nombre completo, apodo, domicilio, ciudad, regi&oacute;n, c&oacute;digo postal, pa&iacute;s, n&uacute;mero de tel&eacute;fono, direcci&oacute;n de correo electr&oacute;nico, etc. a los participantes en el Programa de Protecci&oacute;n de Propiedad Intelectual de SoloChanguitas en la forma que, a nuestra discreci&oacute;n, entendamos necesaria o adecuada en relaci&oacute;n con la investigaci&oacute;n del fraude, infracci&oacute;n de derechos de propiedad industrial o intelectual, pirater&iacute;a, o cualquier otra actividad ilegal. Este derecho ser&aacute; ejercido por SoloChanguitas a efectos de cooperar con el cumplimiento y ejecuci&oacute;n de la ley, independientemente que no exista una orden judicial o administrativa al efecto.</p>
<p>Adem&aacute;s, SoloChanguitas se reserva el derecho (y nos autorizas expresamente a ello) de comunicar informaci&oacute;n sobre sus usuarios a otros usuarios, entidades o terceros cuando haya motivos suficientes para considerar que la actividad de un usuario sea sospechosa de intentar o cometer un delito o intentar perjudicar a otras personas. Este derecho ser&aacute; utilizado por SoloChanguitas a su entera discreci&oacute;n cuando lo considere apropiado o necesario para mantener la integridad y la seguridad de la Comunidad y la de sus usuarios, para hacer cumplir los T&eacute;rminos y Condiciones Generales y dem&aacute;s Pol&iacute;ticas del sitio y a efectos de cooperar con la ejecuci&oacute;n y cumplimiento de la ley. Este derecho ser&aacute; ejercido por SoloChanguitas independientemente que no exista una orden judicial o administrativa al efecto.</p>
<h4>Seguridad. Almacenamiento de la informaci&oacute;n</h4>
<p>SoloChanguitas est&aacute; obligado a cumplir con toda la normativa aplicable en materia de medidas de seguridad aplicables a la Informaci&oacute;n Personal.</p>
<p>SoloChanguitas considera a los datos de sus usuarios como un activo que debe ser protegido de cualquier p&eacute;rdida o acceso no autorizado. Empleamos diversas t&eacute;cnicas de seguridad para proteger tales datos de accesos no autorizados por usuarios de dentro o fuera de nuestra compa&ntilde;&iacute;a. Sin embargo, es necesario tener muy en cuenta que la seguridad perfecta no existe en Internet.</p>
<p>El usuario de SoloChanguitas conoce y acepta expresamente que SoloChanguitas, a su exclusivo criterio, recabe, almacene y monitoree el intercambio de mensajes y correos electr&oacute;nicos entre sus usuarios, efectuado dentro de la comunidad de SoloChanguitas, con el objetivo de contribuir a la seguridad de las relaciones y comunicaciones en la comunidad.</p>
<p>Por ello, SoloChanguitas no se hace responsable por interceptaciones ilegales o violaci&oacute;n de sus sistemas o bases de datos por parte de personas no autorizadas. SoloChanguitas, tampoco se hace responsable por la indebida utilizaci&oacute;n de la informaci&oacute;n obtenida por esos medios.</p>
<p>Todos los datos personales de los usuarios ser&aacute;n almacenados en un fichero automatizado de datos personales. El fichero de Datos Personales de los usuarios de SoloChanguitas reside en EE.UU. El usuario al registrarse en SoloChanguitas confirma que est&aacute; informado de la residencia de este fichero y autoriza esta transferencia internacional de sus datos.</p>
<h4>Cambio en las preferencias de e-mails</h4>
<p>Sin perjuicio que SoloChanguitas quiere mantener a sus usuarios actualizados en todo momento sobre promociones, novedades, cambios, etc. los usuarios pueden seleccionar los e-mails e informaci&oacute;n promocional que gustar&iacute;an recibir de SoloChanguitas.</p>
<p>Si no quieres recibir correos electr&oacute;nicos, puedes desuscribirte cambiando tus preferencias de e-mail siguiendo las instrucciones que proporcionamos en nuestras comunicaciones o bien accediendo a tu cuenta en la secci&oacute;n Mi Perfil. En esa secci&oacute;n podr&aacute;s seleccionar las preferencias para que sean tenidas en cuenta por SoloChanguitas en las futuras comunicaciones o enviando tus preferencias por correo a la direcci&oacute;n postal indicada en estas pol&iacute;ticas.</p>